"""Feature manifest primitives.

The manifest is intentionally small and explicit.  Every feature generated by the
pipeline must have a manifest row so reviewers can check the family, lookback,
and whether future data is used.  For this project, production/research features
must always have ``uses_future=False``.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable, Sequence

import json
import pandas as pd


@dataclass(frozen=True)
class FeatureSpec:
    """Metadata for one generated feature column."""

    name: str
    family: str
    lookback_minutes: int
    uses_future: bool = False
    source: str = "ohlcv_1m"
    available_at: str = "bar_close"
    description: str = ""

    def to_dict(self) -> dict:
        return asdict(self)


def specs_to_frame(specs: Sequence[FeatureSpec]) -> pd.DataFrame:
    """Return a manifest DataFrame from feature specs."""
    return pd.DataFrame([spec.to_dict() for spec in specs])


def specs_to_records(specs: Sequence[FeatureSpec]) -> list[dict]:
    """Return JSON-serializable manifest records."""
    return [spec.to_dict() for spec in specs]


def write_manifest(specs: Sequence[FeatureSpec], path: Path) -> None:
    """Write manifest as JSON or CSV based on file extension."""
    path.parent.mkdir(parents=True, exist_ok=True)
    suffix = path.name.lower()
    if suffix.endswith(".json"):
        with path.open("w", encoding="utf-8") as f:
            json.dump(specs_to_records(specs), f, indent=2, ensure_ascii=False)
    elif suffix.endswith(".csv"):
        specs_to_frame(specs).to_csv(path, index=False)
    else:
        raise ValueError("manifest path must end with .json or .csv")


def read_manifest(path: Path) -> list[FeatureSpec]:
    """Read a JSON/CSV feature manifest."""
    suffix = path.name.lower()
    if suffix.endswith(".json"):
        with path.open("r", encoding="utf-8") as f:
            records = json.load(f)
    elif suffix.endswith(".csv"):
        records = pd.read_csv(path).to_dict(orient="records")
    else:
        raise ValueError("manifest path must end with .json or .csv")
    return [FeatureSpec(**record) for record in records]


def ensure_unique_feature_names(specs: Iterable[FeatureSpec]) -> None:
    """Raise if duplicate feature names exist."""
    seen: set[str] = set()
    duplicates: list[str] = []
    for spec in specs:
        if spec.name in seen:
            duplicates.append(spec.name)
        seen.add(spec.name)
    if duplicates:
        raise ValueError("duplicate feature specs: " + ", ".join(sorted(set(duplicates))))
